### ISSUE TITLE
mikrotik-winbox can't install from snap

### ISSUE THREAD

**Issue by keepalivesrc** [ra1nb0w/mikrotik-winbox-snap#2]
Ubuntu 18.04.3 LTS
mikrotik-winbox can't install from snap,it's removed from snap store.
i try snap install --edge mikrotik-winbox is work installed,but can't Launch

snap install mikrotik-winbox
error: cannot perform the following tasks:
Ensure prerequisites for "mikrotik-winbox" are available (snap not found)

snap install --edge mikrotik-winbox 
mikrotik-winbox (edge) 3.18 from rainbow (rainbow-irh) installed

**Comment by ra1nb0w** [comment]
Removed from snap store.
I am waiting a fix from upstream.

**Comment by keepalivesrc** [comment]
> Removed from snap store.
> I am waiting a fix from upstream.

I see. Thank you.
